name: CI
on: [push, pull_request]

jobs:
  check:
    name: Try build and apply eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - run: npm ci
      - run: npm run build
      - run: npm run lint
